/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:443e5c38-3b6c-4b57-88ab-a49e139fb866",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fq8uD24Rp",
    "aws_user_pools_web_client_id": "d95sl4ir5d102eejg436mq1pj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mgcvyc5fdfgj7cepsmc3rfaapq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
